### ISSUE TITLE
mexw64 compiling 'signed_distance' [persistent precomputation data feature request]

### ISSUE THREAD

**Issue by alecjacobson** [alecjacobson/gptoolbox#1]
Alec: pasted from email:

> Dear Alec Jacobson,
> 
> I would like to use the function signed_distance of your matlab toolbox gptoolbox for my research. Unfortunately, I have been unsuccessful in mexw64 compiling. Hopefully you can give me some help.
> 
> If you already have a mexw64 compiled version of this function, it is probably easiest to just send me this file. Otherwise, this is in short what I have done so far:
> - ```
>        I followed the standard installation instructions on the gptoolbox github site;
>   ```
> - ```
>        I tried to follow the full installation instructions on the gptoolbox github as well though didn’t succeed:
>   ```
> 
> o   I downloaded and extracted libigl and eigen3;
> 
> o   I followed the instructions for compiling libigl as a static library with visual studio. Compilation failed with many errors. Though, I am uncertain if it is necessary to compile a static library of libigl for the function signed_distance.
> -          In matlab, I tried the following line and got multiple errors:
> 
> o   mex -v -largeArrayDims -DMEX -IC:\libigl\include -IC:\eigen3 -O signed_distance.m signed_distance.cpp
> 
> Kind Regards,
>  JM

**Comment by amiralinjm** [comment]
Dr. Jacobson, 

Thank you for your fantastic toolbox. 
I am a Materials science PhD student and I can easily use it, however, I encountered the same problem compiling 'signed_distance' and 'point_mesh_squared_distance' .

If you already have a mexw64 or mexmaci64 (as I have acess to OS X platform)  compiled version of these functions, I greatly appreciate of you  send me thses files. 

However trying to compile on my Windows: 
I am running Windows10 / MATLAB 2016b / VS2015
Version:
Boost: 1_64
CGAL: 4.7
Eigen: 3.3.3
libigl: https://github.com/libigl/libigl/tree/4ccac53005994f695eea123cd85e92be27caecb2

I used the same code format on this post:

` mex -v -largeArrayDims -DMEX ...
  -IC:\dev\libigl\include ...
  -IC:\dev\eigen ...
  -IC:\dev\CGAL-4.7\include ...
  -IC:\dev\CGAL-4.7\build\include\ ...
  -IC:\dev\CGAL-4.7\auxiliary\gmp\include ...
  -IC:\dev\boost_1_64_0\ ...
  -LC:\dev\CGAL-4.7\build\lib\ -lCGAL-vc110-mt-4.7 -lCGAL_Core-vc110-mt-4.7 ...
  -LC:\dev\CGAL-4.7\auxiliary\gmp\lib -llibgmp-10 -llibmpfr-4 ...
  -LC:\dev\boost_1_64_0\lib64-msvc-11.0 ...
  -lboost_thread-vc110-mt-1_64 -lboost_system-vc110-mt-1_64 ...
  -llibboost_thread-vc110-mt-1_64 -llibboost_system-vc110-mt-1_64 ...
  -llibboost_date_time-vc110-mt-1_64 ...
  -llibboost_chrono-vc110-mt-1_64 ...
  signed_distance.cpp
`
Errors: C4305,C4267,C4244:
`c:\dev\libigl\include\igl\EPS.h(16): warning C4305: 'initializing': truncation from 'double' to 'float'
c:\dev\libigl\include\igl\EPS.h(17): warning C4305: 'initializing': truncation from 'double' to 'float'
c:\dev\libigl\include\igl\exterior_edges.cpp(91): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\dev\libigl\include\igl\exterior_edges.cpp(92): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\dev\libigl\include\igl\winding_number.cpp(34): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const int', possible
loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\winding_number.cpp(34): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const int', possible
loss of data
        with
        [
            Derived=Eigen::Matrix<int,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\winding_number.cpp(40): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible
loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\winding_number.cpp(40): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const int',
possible loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\signed_distance.cpp(29): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible
loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\signed_distance.cpp(29): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const int',
possible loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\signed_distance.cpp(325): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const int', possible
loss of data
        with
        [
            Derived=Eigen::Matrix<int,-1,-1,0,-1,-1>
        ]
c:\dev\libigl\include\igl\signed_distance.cpp(325): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const int', possible
loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
C:\Users\user\Documents\MATLAB\gptoolbox_full\mex\signed_distance.cpp(37): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss
of data
C:\Users\user\Documents\MATLAB\gptoolbox_full\mex\signed_distance.cpp(37): warning C4267: 'initializing': conversion from 'size_t' to 'const int',
possible loss of data
C:\Users\user\Documents\MATLAB\gptoolbox_full\mex\signed_distance.cpp(183): error C2665: 'igl::signed_distance_winding_number': none of the 3 overloads
could convert all the argument types
c:\dev\libigl\include\igl\signed_distance.cpp(293): note: could be 'void igl::signed_distance_winding_number(const igl::AABB<Eigen::MatrixXd,3> &,const
Eigen::MatrixXd &,const Eigen::MatrixXi &,const igl::WindingNumberAABB<Eigen::Vector3d> &,const Eigen::Matrix<double,1,3,1,1,3> &,double &,double &,int
&,Eigen::Matrix<double,1,3,1,1,3> &)'
C:\Users\user\Documents\MATLAB\gptoolbox_full\mex\signed_distance.cpp(183): note: while trying to match the argument list '(igl::AABB<Eigen::MatrixXd,3>,
Eigen::MatrixXd, Eigen::MatrixXi, igl::WindingNumberAABB<Eigen::RowVector3d>, const Eigen::RowVector3d, double, double, int, Eigen::RowVector3d)'`

I followed exactly same instructions on this post, could you please help me with this.

Regards,
AN
