### ISSUE TITLE
How can I get vertices color of `ply` files

### ISSUE THREAD

**Issue by greatwallet** [alecjacobson/gptoolbox#107]
I tried with `readPLY` but it only returns vertices' positions and normals.

**Comment by alecjacobson** [comment]
my `readPLY` is just a wrapper for Gabriel Peyre's `external/read_ply.m`. You might hunt around in that function to see if it's already reading colors and normals.

**Comment by rFalque** [comment]
A dirty and lazy (but quick) workaround is to use the built-in `pcread` function for pointclouds in matlab (e.g., `ptCloud = pcread('teapot.ply');`). 

Then the colors are available in `ptCloud.Color`

**Comment by greatwallet** [comment]
> A dirty and lazy (but quick) workaround is to use the built-in `pcread` function for pointclouds in matlab (e.g., `ptCloud = pcread('teapot.ply');`).
> 
> Then the colors are available in `ptCloud.Color`

Thanks! Actually that was exactly what I did, though I think it might be great if `readPLY` could provide both functions.
