### ISSUE TITLE
不支持将脚本 signed_distance 作为函数执行: E:\MATLAB_File\gptoolbox\mex\signed_distance.m

### ISSUE THREAD

**Issue by xjfeng950418** [alecjacobson/gptoolbox#163]
Executing the script signed_distance as a function is not supported.
My matlab version is R2021b.

**Comment by alecjacobson** [comment]
What happens if you issue

which signed_distance

**Comment by xjfeng950418** [comment]
I ran this script [Offset surface of triangle mesh in matlab](https://www.alecjacobson.com/weblog/4708.html) in my matlab.
The error is reported as the above issue.
I just found your answer in  [STL-offset issue #44](https://github.com/alecjacobson/gptoolbox/issues/44), and travelled to mex/ file to find the compile method.
Following your instructions, my issues is settled now.
Thank you very much!

**Comment by Cp675516471** [comment]
> I ran this script [Offset surface of triangle mesh in matlab](https://www.alecjacobson.com/weblog/4708.html) in my matlab. The error was reported as the above issue. I just found your answer in [STL-offset issue #44](https://github.com/alecjacobson/gptoolbox/issues/44), and travelled to mex/ file to find the compiling method. Following your instructions, my issue is settled now. Thank you very much!

Hello，i got problem to use the function named signed_distance too and i tried to compel the files but failed！ here are my problem ：


CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.22631.
-- MSVC -> forcing use of statically-linked runtime.
-- vcpkg was not found in system and will be installed to D:/AppInstallFile/AZMatlab/toolbox/alecjacobson-gptoolbox-1b2e0f1/external/vcpkg ...
CMake Error at CMakeLists.txt:100 (execute_process):
  execute_process failed command indexes:

    1: "Abnormal exit with child return code: no such file or directory"



-- Configuring incomplete, errors occurred!
