### ISSUE TITLE
[Question] Are points inside a triangle mesh?

### ISSUE THREAD

**Issue by oqilipo** [alecjacobson/gptoolbox#17]
I'm looking for a fast way (mex) to detect if points are inside a closed triangle mesh.

I saw "in_element_aabb", but this seems to be for tet meshes only?

Is there another function for triangle meshes in the toolbox that I may have missed?

Thanks in advance

**Comment by alecjacobson** [comment]
Are your points and mesh living in 2D (the plane) or in 3D (the mesh is a
surface)?

**Comment by oqilipo** [comment]
3D points and a surface mesh with vertices [n*3] and faces [m*3].

**Comment by alecjacobson** [comment]
If your mesh is the closed manifold boundary of a solid object (no
boundaries/ self-intersections etc.) then you should use `signed_distance`,
the sign will tell you whether your inside or outside.

If you mesh is messy and you want a fractional value telling you (roughly)
how much inside vs outside the point is, you should use `winding_number`.

**Comment by oqilipo** [comment]
Ahh, for sure "signed_distance".

Yes the mesh is the closed manifold boundary of a solid object.

I've tested it and it works 10 times faster then the pure matlab function I used before.

´Thank you very much!
