### ISSUE TITLE
Choice of signs/constants in cotmatrix / lscm ?

### ISSUE THREAD

**Issue by alecjacobson** [alecjacobson/gptoolbox#19]
From personal email:

> Your cotmatrix returns -1/(4*A_i)*(cot + cot)?
> (negative sign and an extra 2, why this choice?)
Just to be clear. My `cotmatrix` returns: `L(i,j) = 1/4 * (cot(alpha) + cot(beta))` for an internal edge (i,j) with opposite angles alpha and beta. This means the off-diagonal entries are _positive_ for an (intrinsically) Delaunay mesh and the diagonal (`L(i,i) = -sum_j!=i L(i,j)`) is  negative.

I think the minus sign  (w.r.t. what other people use) is reasonable justified.

Consider the discrete Dirichlet energy for piecewise linear function `u` on a 3D triangle mesh:

    1/2*u'*G'*A*G*u

where `G` is a #3F by #V matrix that computes the piecewise constant gradient xyz-components per-triangle, and `A` is a diagonal matrix repeating triangle areas (integrating the gradients).

[Green's first identity](https://en.wikipedia.org/wiki/Green%27s_identities) tells us that in the continuous world: 1/2*<∇u,∇u> = -1/2*<u,∆u> + boundary term.

So if we repeat this in the discrete world, we'd expect that: 

    1/2*u'*G'*A*G*u = = -u'*M*(M\L)*u = -u'*L*u

where `M` is a per vertex mass matrix (that immediately gets cancelled out), `M\L` computes the "point wise" or "integral average" Laplacian value and `L` is the Laplacian from `cotmatrix`.

[You can actually verify this equality using `G = grad(V,F);` and `A = repdiag(diag(sparse(doublearea(V,F)/2)),size(F,2))`]

The one-half just got swallowed into `L`, I guess. It's here to stay for legacy reasons.

**_One important consequence_**: is that my `L` is _negative_ semi-definite. Solvers like, `chol` will vomit on just `L`, but you just have to hit the right and left sides of your solve with a minus sign.

> I am comparing your stuff with [Mullen et al. SGP’08] as in that paper: `L_c = L_d - A`, 
> 
> while in your case you have: 
>` L_c = -L_d + 2*A.`
 
This is a direct consequence of the "-1/2" above and the fix below.

> (haven’t looked at the reason for the extra 2 on A yet)

> Also, why did you need to do this flip?
>
>     % Flip XY
>     P = sparse(1:2*n,[n+(1:n) 1:n],1,2*n,2*n);
>     Q = -repdiag(L,2) + 2*A;
>     Q = P’*Q*P;

Seems this was a very silly way of negating the area. It should have been and now (ba8d1e5) is just:

    Q = -L - 2*A;

**Comment by ataiya** [comment]
Thanks Alec! Now everything is clear, the "-" is because of legacy decisions (in disagreement with how the operator is written on many papers) and the 2*A is to compensate for the fact that your L=-2*L_"classic"

Regarding the P for "Flip XY" I see what you mean, I actually did that myself :)
I was just wondering whether it was something I was supposed to do and I was unaware of!

By the way, perhaps you have a better intuition than me. 
**Any clue on why the following two produce the same result?** 
(I did this test while I was trying to remove the "Flip XY"):
```
Q = repdiag(L,2)-A;
Q = repdiag(L,2)+A;
```

**Comment by alecjacobson** [comment]
I don't think it does, does it? Are you sure you're not also flipping the sign of `L`, too? Then you'd be comparing `Q` vs. `-Q` and my solver (`min_quad_with_fixed`) will return the same result since it's actually finding a stationary point of the energy (corresponding to the minimum only for positive definite energies `Q` and maximum for negative definite energies `-Q`).

**Comment by ataiya** [comment]
Yes, I am sure I am only flipping one (see the zip via email)
I am not using your solver but matlab _quadprog_.

**Comment by alecjacobson** [comment]
In your example does it still happen if you have more than two constraints?

**Comment by ataiya** [comment]
Very good suggestion for a test :)
![camel_lscm](https://cloud.githubusercontent.com/assets/4480573/20027271/ddd7f494-a2cc-11e6-9fcb-a75bd3e469b2.gif)

Indeed they are different, still puzzling why a result (rather than garbage) is even generated :)

**Comment by alecjacobson** [comment]
I never found a satisfying way to show textures on a  general triangle mesh using pure matlab.
