### ISSUE TITLE
Outdated icosahedron function

### ISSUE THREAD

**Issue by oqilipo** [alecjacobson/gptoolbox#24]
After updating the gptoolbox I had a conflict with the external icosahedron function, because it's an old version from 2009

The current version from 2016 can be found here:
https://github.com/pgagarinov/spheretri

spheretri may be be added as submodule?

Thanks and kind regards

**Comment by alecjacobson** [comment]
Adding a submodule for the icosahedron seems like overkill. I'll happily accept a pull request for the new function if necessary.

**Comment by oqilipo** [comment]
Done.

kind regards
