### ISSUE TITLE
Tab completion error in Matlab 2017a

### ISSUE THREAD

**Issue by wucm1994** [alecjacobson/gptoolbox#28]
Hi Alec,
When I use add_gptoolbox_tab_completion in my Matlab 2017a environment, a failure occurs as:

```
Error tabcomplete>getCurrentXmlDefs (line 170)
E:\Program Files\MATLAB\R2017a\toolbox\local\TC.xml was not found - cannot set tab-completions

Error tabcomplete (line 106)
    [defs,tcXmlFilename] = getCurrentXmlDefs;

Error add_gptoolbox_tab_completion>@(x)tabcomplete(x{1},x{2})

Error add_gptoolbox_tab_completion (line 75)
  cellfun(@(x) tabcomplete(x{1},x{2}),L,'UniformOutput',false);
```

How to fix this error? Thanks.

**Comment by alecjacobson** [comment]
Apparently the `TC.xml` tab-completion is [obsolete](https://ch.mathworks.com/matlabcentral/answers/306157-how-to-configure-tab-completion-for-my-function-in-matlab-2016). There is now a more powerful but convoluted way of adding tab completion by placing a `functionSignatures.json` file in the same directory as the functions. See for example:

https://github.com/alecjacobson/gptoolbox/blob/master/mesh/functionSignatures.json

I suppose I ought to just delete the old tab completion functions...
