### ISSUE TITLE
Shrink wrap mesh?

### ISSUE THREAD

**Issue by oqilipo** [alecjacobson/gptoolbox#32]
Hello 

My question is if something similar could be done with this toolbox?

There is a function in Materialise Magics to Shrink Wrap a mesh:
You can define:
- Sample Interval [mm]
- Gap Fill [mm]
- Organic Shape [True/False]
- Add extra thickness [mm]

Here is an example:
Original:
![original](https://user-images.githubusercontent.com/15254908/28595541-93a8279e-7194-11e7-9701-5ba404cef4d6.PNG)
Shrink Wrap with 2mm Sample Interval, 20mm Gap Fill and Organic Shape True:
![shrinkwrap_sampleinterval-2mm_gapfill-20mm_organicshape-true](https://user-images.githubusercontent.com/15254908/28595544-96ef814a-7194-11e7-99e4-ef233e6fec04.PNG)

Thanks in advance
oqilipo

**Comment by alecjacobson** [comment]
I'm not sure exactly what Materialise Magics is doing. If I had to guess, it would be that they're using the [closing](https://en.wikipedia.org/wiki/Closing_(morphology)) operation. You can get an approximate closing very easily using the `signed_distance_isosurface` function in Matlab.

```
% parameter controlling gap size to merge
sigma = 0.5;
% Dilate original
 [V1,F1] = signed_distance_isosurface(V,F,'Level',sigma);
% Erode dilation
 [V2,F2] = signed_distance_isosurface(V1,F1,'Level',-sigma);
```

You'll have to play around with the parameters of `signed_distance_isosurface`.

Here's an animation I made using this type of closing for various `sigma`s.

![iwires-shrink](https://user-images.githubusercontent.com/2241689/28644764-da05e2b4-7228-11e7-82b3-420c0aaee481.gif)

**Comment by oqilipo** [comment]
Looks promising. I will play around with the parameters.

**Thanks a lot!**

![output_gq9nnl](https://user-images.githubusercontent.com/15254908/28659425-b26d8c84-72af-11e7-92a9-1104e6ed8bf5.gif)
