### ISSUE TITLE
mex problems of gptoolbox

### ISSUE THREAD

**Issue by yqwang2006** [alecjacobson/gptoolbox#4]
I'm using the gptoolbox to generate some sdf data from 'off' files. However, the gptoolbox would make MATLAB  crash. First, I compiled the signed_distance_isosurface.cpp in 'mex' dir using next command:

' mex -g -largeArrayDims -DMEX  CXXFLAGS="\$CXXFLAGS -std=c++11"...
   -I/usr/local/igl/libigl/include ...
   -I/usr/include/eigen3 ...
   -I/usr/include ...
  -L/usr/lib ...
  -lCGAL -lCGAL_Core -lgmp -lmpfr... 
  -lboost_thread -lboost_system ...
   signed_distance_isosurface.cpp'

This process would not generate any errors. However, MATLAB would crash when I tried to run a demo. The demo code is:

addpath('mesh');
addpath('mex');
[V,F,UV,C,N] = readOFF( 'bed.off');
[OV,OF] = signed_distance_isosurface(V,F);

The error is shown in next fig. Could you please help me? Thanks.

![image](https://cloud.githubusercontent.com/assets/7324348/7875864/614757a0-05f5-11e5-8297-8ea59d00d38a.png)

**Comment by alecjacobson** [comment]
Which Eigen Version do you have? Which CGAL version? Which Matlab?

**Comment by yqwang2006** [comment]
The dependent lib versions are: 
cgal: 4.6
boost: 1.58
eigen: 3.2.4

**Comment by yqwang2006** [comment]
matlab: 2014b

**Comment by alecjacobson** [comment]
Can you share your chair?

**Comment by yqwang2006** [comment]
OK, I'll send you by email due to github doesn't support the file type.

**Comment by alecjacobson** [comment]
Seems to be a bug. For now I'd suggest removing any degenerate faces from your input mesh.

**Comment by alecjacobson** [comment]
This no longer crashes (at least by 4ced5ebaf6a78c0837f40b9b01f2e07616950cc2 but probably much earlier).

**Comment by alecjacobson** [comment]
BTW, I used:

```matlab
[OV,OF] = signed_distance_isosurface(V,F,'SignedDistanceType','unsigned','Level',0.3,'DistanceBound',0.004,'RadiusBound',0.004);
```
to generate this:

![image](https://cloud.githubusercontent.com/assets/2241689/16084959/88168a92-32e8-11e6-91a9-a1b6c94bd413.png)
