### ISSUE TITLE
skinning_transformations.m: 3D support for bone controls

### ISSUE THREAD

**Issue by oqilipo** [alecjacobson/gptoolbox#43]
Hello

Would it be possible to add the 3D support for bone controls in skinning_transformations.m?

Kind regards
oqilipo

**Comment by alecjacobson** [comment]
I'm not actively developing on this. I see no reason that it couldn't be done, but I probably won't do it. I would merge a clean PR if submitted.

**Comment by oqilipo** [comment]
For now I've only used the point controls and this works very well.

Thanks for the code
