### ISSUE TITLE
Error in tsurf function 

### ISSUE THREAD

**Issue by FeazAlkadi** [alecjacobson/gptoolbox#46]
In this example
http://www.alecjacobson.com/weblog/?p=4708

I was able to get SV and SF.
But when i run the second section of the script to plot the STL and see it as follow:

clf;
hold on;
t = tsurf(F,V,'EdgeColor','none',fsoft, 'FaceVertexCData',repmat(blue,size(V,1),1),'FaceAlpha',1+(iso<0)(0.35-1),fphong);
ts = tsurf(SF,SV,'EdgeAlpha',0.2+(iso<0)(0-0.2),fsoft,'FaceVertexCData',repmat(orange,size(SV,1),1),fphong,'FaceAlpha',1+(iso>0)(0.2-1));
apply_ambient_occlusion(ts);
hold off;
axis equal;
view(-20,20)
camlight;
t.SpecularStrength = 0.04;
l = light('Position',[5 -5 10],'Style','local');
add_shadow(t,l,'Color',0.8[1 1 1],'Fade','local','Ground',[0 0 -1 min([V(:,3);SV(:,3)])]);
set(gca,'pos',[0 0 1 1])
set(gca,'Visible','off');
set(gcf,'Color','w');
drawnow;

I get the following error:

Error using matlab.graphics.primitive.Patch/set
Error setting property 'FaceVertexCData' of class 'Patch':
Value must be an Nx1 or Nx3 array of numeric type

Error in tsurf (line 130)
set(t_copy,varargin{v:end});

Error in Untitled (line 29)
t = tsurf(F,V,'EdgeColor','none',fsoft, 'FaceVertexCData',repmat('blue',size(V,1),1),'FaceAlpha',1+(iso<0)*(0.35-1),fphong);

Thought V,F,SV and SF are all Nx3 array of type double
Does any any one have an idea what would be the problem???

Thank you

**Comment by alecjacobson** [comment]
repmat('blue',size(V,1),1)

should be

    repmat(blue,size(V,1),1)

**Comment by FeazAlkadi** [comment]
**I did so, as following:
and now i got this error !**

Undefined function 'per_vertex_normals' for input arguments of type 'double'.

Error in apply_ambient_occlusion/apply_ambient_occlusion_helper (line 58)
      N = per_vertex_normals(V,F);

Error in apply_ambient_occlusion (line 150)
    [AOii,Cii] = apply_ambient_occlusion_helper(tii,AOii,Cii,factor,unoriented);

Error in STLoffset (line 31)
apply_ambient_occlusion(ts);

**Do you have an idea what would be the problem ?**

**Comment by FeazAlkadi** [comment]
**SORRY, I posted the wrong error at the beginning. I just updated that.**

**Comment by alecjacobson** [comment]
have you changed `ambient_occlusion.m`? Do you have another file called `ambient_occlusion.m` in your path?

**Comment by FeazAlkadi** [comment]
**No i didn't. And I don't have another file.** 
**Does it need to be compiled too? **
**because I tried to compile it as** oqilipo **advised me to do for the function** signed_distance. 

clearvars


path_to_eigen='C:\Users\faa23\Desktop\3D_DiskTop\MatlabCodes\iges (original)\eigen-eigen-';
% Check if the eigen path is correct
assert(exist([path_to_eigen '\Eigen\Core'],'file')==2)

path_to_libigl='C:\Users\faa23\Desktop\3D_DiskTop\MatlabCodes\iges (original)\libigl';

%%

MEXOPTS={'-v','-largeArrayDims','-DMEX'};

EIGEN_INC= ['-I' path_to_eigen];

LIBIGL_INC=['-I' path_to_libigl '\include'];
LIBIGL_FLAGS='-DIGL_SKIP';
LIBIGL_LIB={'-DIGL_SKIP'};
LIBIGL_LIBMATLAB='-DIGL_SKIP';
LIBIGL_LIBCGAL='-DIGL_SKIP';
LIBIGL_LIBCORK='-DIGL_NO_CORK';
LIBIGL_BASE={LIBIGL_INC, LIBIGL_FLAGS,LIBIGL_LIB{:}, LIBIGL_LIBMATLAB};

mex( ...
  MEXOPTS{:}, ...
  LIBIGL_BASE{:},EIGEN_INC, ...
  'ambient_occlusion.cpp');

**But there was a an error as follow:**

Error using mex
ambient_occlusion.cpp
c:\users\faa23\desktop\3d_disktop\matlabcodes\iges (original)\libigl\include\igl\EPS.h(16): warning C4305: 'initializing': truncation from 'double' to 'float'
c:\users\faa23\desktop\3d_disktop\matlabcodes\iges (original)\libigl\include\igl\EPS.h(17): warning C4305: 'initializing': truncation from 'double' to 'float'
c:\users\faa23\desktop\3d_disktop\matlabcodes\iges (original)\libigl\include\igl\embree\EmbreeIntersector.h(24): fatal error C1083: Cannot open include file: 'embree2/rtcore.h': No such file or directory



Error in STLoffset (line 25)
mex( ...


**The thing is that I did find file embree2 in libigl !!!**

**Comment by alecjacobson** [comment]
Sorry, I forgot that it's a Mex file. Yes, it needs to be compiled as
you're trying.

Looks like you're not including the path to the embree header files. Take a
look in gptoolbox_mexopts. Not sure where your installation is or if it's
different on W*ndows.

**Comment by FeazAlkadi** [comment]
Thank you so much Alec.
I hope someone can step up here :)

**Comment by FeazAlkadi** [comment]
Do you think think I should close this and open a new issue?
