### ISSUE TITLE
Typo in schur_complement.m

### ISSUE THREAD

**Issue by CsatiZoltan** [alecjacobson/gptoolbox#50]
`BABTFUN` is not defined on this line:
https://github.com/alecjacobson/gptoolbox/blob/5383baccc0e773b16ae7e3b3d9c59795bfa87aa0/matrix/schur_complement.m#L113
I suppose you should rather use `BABTCFUN`.

Other: On a sparse system of total size 3108x3108, with `A` being indefinite but symmetric, this function is considerably slower than `\`. I have tried using [Factorize](https://fr.mathworks.com/matlabcentral/fileexchange/24119-don-t-let-that-inv-go-past-your-eyes--to-solve-that-system--factorize-), which is only 3 times slower in my case than `\` (but it has the advantage that the factors can be precomputed, so they are usable with different right-hand-sides).

**Comment by alecjacobson** [comment]
This solver is good for very specific scenarios. In general, I'd recommend using min_quad_with_fixed (similar to what Factorize does, but a more friendly interface for constrained energy minimization ).
