### ISSUE TITLE
In file readMSH.cpp shouldn't it include readMESH.h ?

### ISSUE THREAD

**Issue by sidgairo18** [alecjacobson/gptoolbox#61]

**Comment by vmonkey** [comment]
I think the same. The compilation does not go through, so I modified the code:

`#include <igl/readMSH.h>`
to 
`#include <igl/readMESH.h>`

and 

`MatrixXi F;`
to
`MatrixXi F, T;`

and, finally,

`if(!igl::readMSH(file_path,V,F))` to
`if(!igl::readMESH(file_path,V,T,F))`

Now it compiles fine but I am not sure if this is correct (if the code does what it is supposed to do).

**Comment by sidgairo18** [comment]
Usually Mr. Jacobson is pretty prompt in handling issues. Would be grateful if he could relieve us of this problem. :)

**Comment by alecjacobson** [comment]
readMSH is distinct from readMESH, the issue is that this relied on a function of libigl that was not yet available in the libigl master branch. The solution is to `git pull` in your libigl

**Comment by vmonkey** [comment]
Yes, this works, indeed. Thanks.
