### ISSUE TITLE
Error in subtracting two stls

### ISSUE THREAD

**Issue by KiyaValentine** [alecjacobson/gptoolbox#69]
I'm encountering an error in using the mesh boolean winding number function, the output reads as follows:

Undefined function or variable 'selfintersect'.

Error in mesh_boolean_winding_number (line 31)
  [W,SFG,~,J,IM] = selfintersect(VU,FG);

I'm not entirely sure I've installed the toolbox correctly, is there a simple instruction guide on how to do so?
Bear in mind that I'm not a terribly apt programmer.
Does anyone know of a solution to this?

Regards,

Garrick

**Comment by alecjacobson** [comment]
You'll need to compile the mex functions in the mex/ directory. The new cmake build should hopefully work and you can follow the README.md
