### ISSUE TITLE
quadslerp and quadmultiply

### ISSUE THREAD

**Issue by TerranRush** [alecjacobson/gptoolbox#74]
In `quadslerp.m`, the ')' of the `sin` function are put in wrong places, should be:
```
s0 = sin( (1-t) .* theta)./sinTheta;
s1 = sin(    t  .* theta)./sinTheta;
```

In `quadmultiply.m`, the code after `% enforce unit length` get wrong results when input `q` has multiple quats. It could be modified as:
```
mag= qout(:,1).* qout(:,1) +  qout(:,2).* qout(:,2) +  qout(:,3).* qout(:,3) +  qout(:,4).* qout(:,4);

if( abs(mag-1.0)<0.0001)
    qout=qout;
else
    
    mag=1.0./sqrt( mag);
    qout(:,1)=qout(:,1).* mag;
    qout(:,2)=qout(:,2).* mag;
    qout(:,3)=qout(:,3).* mag;
    qout(:,4)=qout(:,4).* mag;
end
```

**Comment by alecjacobson** [comment]
thanks, fixed quatslerp.m (seems I wasn't using this function). The normalization in quatmultiply.m probably shouldn't be there at all (removed).
