### ISSUE TITLE
Mesh Boolean problem

### ISSUE THREAD

**Issue by Boccio90** [alecjacobson/gptoolbox#75]
i've 2 stl files, and i'm tryngo to do simple boolean operation in matlab, 
i'm loading the two meshes with mesh_load and then i get this error while doing mesh_boolean,
some suggestion?

Error using intersect (line 80)
Not enough input arguments.

Error in importare (line 16)
[V2,F2]= mesh_boolean(V,F,V1,F1, intersect);

**Comment by alecjacobson** [comment]
`intersect` should be `"intersect"`

**Comment by Boccio90** [comment]
my bad, but i've already tried 'intersect' and still got errors.

Attempt to execute SCRIPT mesh_boolean as a function:

it's probably a problem of path?

**Comment by alecjacobson** [comment]
what do you see if you issue

     which mesh_boolean

**Comment by Boccio90** [comment]
only this file.

C:\Users\Utente\Desktop\Matlab\Importare STL\alecjacobson-gptoolbox-8c1bad1\mex\mesh_boolean.m

**Comment by alecjacobson** [comment]
Everything in the mex/ folder needs to be compiled. The .m files there only exist so `help` can be generated. See the mex/README.md for instructions 

https://github.com/alecjacobson/gptoolbox/tree/master/mex

**Comment by Boccio90** [comment]
cmake ..
Undefined function or variable 'cmake'.

Probably i'm too new to matlab to do such things ;)
sorry for wasting your time

**Comment by alecjacobson** [comment]
`cmake` needs to be issued on the terminal (not in Matlab).

You might need to install cmake first.

(.mex files are actually C++ programs that are compiled in a way that matlab can call them as functions. So it might take some getting familiar with before attempting to compile this.).

**Comment by Boccio90** [comment]
i've made a little step forward with cmake, but now when i compile i got this error:

CMake Error at cmake/FindELTOPO.cmake:22 (message):
  could NOT find LIBELTOPO_INCLUDE_DIR
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

any clue?

**Comment by alecjacobson** [comment]
The new CMakeLists.txt might handle your issue better. If you happen to try again, let me know if it works.
