### ISSUE TITLE
FindLIBIGL.cmake problem with newer versions of libigl

### ISSUE THREAD

**Issue by albertofpena** [alecjacobson/gptoolbox#76]
Hi!

Yesterday I tried to compile mex files on a Mac and had this error:
```
CMake Error at cmake/FindLIBIGL.cmake:36 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:34 (find_package)
```

It seems to be a problem with the line 35 of FindLIBIGL.cmake. The cmake folder in libigl changed from 'shared/cmake' to just 'cmake', so replacing
`list(APPEND CMAKE_MODULE_PATH "${LIBIGL_INCLUDE_DIR}/../shared/cmake")`
with
`list(APPEND CMAKE_MODULE_PATH "${LIBIGL_INCLUDE_DIR}/../cmake")`
fixed the error for me.

I am not sure if this should be changed in the repository or if there is a way to maintain the backwards compatibility with older versions of libigl, but I hope this helps if anyone meets this error.

Thanks for your work.

**Comment by maxfrei750** [comment]
I made a PR (#77) which should fix this, while maintaining backwards compatibility.

**Comment by alecjacobson** [comment]
Let me know if there's other/more issues.
