### ISSUE TITLE
remove_duplicate_vertices does not use the epsilon parameter as significant digit

### ISSUE THREAD

**Issue by rarora7777** [alecjacobson/gptoolbox#81]
The input description for [`mesh/remove_duplicate_vertices.m`](https://github.com/alecjacobson/gptoolbox/blob/master/mesh/remove_duplicate_vertices.m) suggests that `epsilon` is the "uniqueness tolerance (significance digit)". However, the current behaviour of the function does not comply with this definition.

Changing line 52 to this should do the trick:
`[~,SVI,SVJ] = unique(round(V*(10^epsilon)),'rows','stable');`

**Comment by alecjacobson** [comment]
Fixed in  f584ecd, but note that documentation changed so the epsilon is clearly a fractional input (and removed the `10*`
