### ISSUE TITLE
'sudo make' error with CGAL files

### ISSUE THREAD

**Issue by yardasol** [alecjacobson/gptoolbox#83]
I am trying to build this library so I can compile the code into mex. In running `make` once I have run `sudo cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..` gives me many errors, the first one being 
`gptoolbox/mex/external/libigl/external/cgal/Installation/lib/cmake/CGAL/../../../../Number_types/include/CGAL/gmpxx.h:45:10: error: 
 'gmpxx.h' file not found with <angled> include; use "quotes" instead
#include <gmpxx.h>`

This may be a problem on the computer as I have had similar issues when running `make` for other libraries as well.

**Comment by alecjacobson** [comment]
This seems like a CGAL issue that I wouldn't quite know how to solve. It's
also suspicious that you're doing `sudo make` instead of just `make`

>

**Comment by yardasol** [comment]
I have to use `sudo make` because otherwise I get this:

`[  1%] Built target impaste
[  1%] Building CXX object CMakeFiles/wire_mesh.dir/wire_mesh.cpp.o
error: unable to open output file 'CMakeFiles/wire_mesh.dir/wire_mesh.cpp.o':
      'Permission denied'`

Also, the CGAL issue is with the CGAL files that are built/included in gptoolbox. Is it possible that it is an issue with the compiler?

**Comment by alecjacobson** [comment]
Interesting. That might mean you're just in a folder that you don't have
write access to. The CGAL issue is strange. I know that everything works
with the CGAL that's auto-downloaded using the libigl cmake.
-Alec

**Comment by yardasol** [comment]
I previously installed CGAL for another library (pcl). Could that be what is causing the make step to go haywire?

**Comment by yardasol** [comment]
I fixed the issue by installing GMP with Homebrew
