### ISSUE TITLE
edge_cylinders: Triangle (line 223) The system cannot find the path specified.

### ISSUE THREAD

**Issue by Frank-Dz** [alecjacobson/gptoolbox#88]
Hi all~ When I use the function:

[CV,CF,CJ,CI] = edge_cylinders(V,E,'Thickness',10);

I get the following **warnings**:
Dear Ladislav, is there a standard place to put executables on a pc?Could you put triangle there and change this accordingly?Thanks, Alec 
  In path_to_triangle (line 11)
  In triangle (line 217)
  In fill_holes (line 28)
  In edge_cylinders (line 220)

and the following **errors**:
triangle (line 223)
The system cannot find the path specified.

The input file is quite simple:
I read the file below into V and E, then pass them to the function.

v 0 0.850651 0.525731
v 0 0.680521 0.420585v 0 1.02078 0.630877
l 1 2
v 0 0.850651 -0.525731
v 0 0.680521 -0.420585v 0 1.02078 -0.630877
l 3 4
v 0 -0.850651 0.525731
v 0 -0.680521 0.420585v 0 -1.02078 0.630877
l 5 6
v 0 -0.850651 -0.525731
v 0 -0.680521 -0.420585v 0 -1.02078 -0.630877
l 7 8
v 0.850651 0.525731 0
v 0.680521 0.420585 0v 1.02078 0.630877 0
l 9 10
v 0.850651 -0.525731 0
v 0.680521 -0.420585 0v 1.02078 -0.630877 0
l 11 12
v -0.850651 0.525731 0
v -0.680521 0.420585 0v -1.02078 0.630877 0
l 13 14
v -0.850651 -0.525731 0
v -0.680521 -0.420585 0v -1.02078 -0.630877 0
l 15 16
v 0.525731 0 0.850651
v 0.420585 0 0.680521v 0.630877 0 1.02078
l 17 18
v -0.525731 0 0.850651
v -0.420585 0 0.680521v -0.630877 0 1.02078
l 19 20
v 0.525731 0 -0.850651
v 0.420585 0 -0.680521v 0.630877 0 -1.02078
l 21 22
v -0.525731 0 -0.850651
v -0.420585 0 -0.680521v -0.630877 0 -1.02078
l 23 24

**Comment by bbrrck** [comment]
Hello, as indicated, the problem is that the function [path_to_triangle.m](https://github.com/alecjacobson/gptoolbox/blob/master/wrappers/path_to_triangle.m) cannot find path to Triangle. You will need to download and compile Triangle, e.g. from the [official website](https://www.cs.cmu.edu/~quake/triangle.html) or using the [libigl mirror](https://github.com/libigl/triangle). You'll then need either to add the Triangle binary to your path, or manually modify [path_to_triangle.m](https://github.com/alecjacobson/gptoolbox/blob/master/wrappers/path_to_triangle.m).

**Comment by Frank-Dz** [comment]
> Hello, as indicated, the problem is that the function [path_to_triangle.m](https://github.com/alecjacobson/gptoolbox/blob/master/wrappers/path_to_triangle.m) cannot find path to Triangle. You will need to download and compile Triangle, e.g. from the [official website](https://www.cs.cmu.edu/~quake/triangle.html) or using the [libigl mirror](https://github.com/libigl/triangle). You'll then need either to add the Triangle binary to your path, or manually modify [path_to_triangle.m](https://github.com/alecjacobson/gptoolbox/blob/master/wrappers/path_to_triangle.m).

ok~ I will have a try. I thought the Triangle was a part of gptoolbox. Thanks for your kind help and guidance.

Best,
Frank
